[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "*"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.17"
bevy = "0.15.2"

[build-dependencies]
tonic-build = "*"
